config/routes.rb
Rails.application.routes.draw do
  resources :pseudos do
    member do
      post "choisir"
      
    end
    collection do
      post "quitter"
    end
  end
  devise_for :users
  resources :users
  resources :comments
  resources :posts
  resources :messages
  resources :rooms
  root to: "rooms#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/pseudo.rb
class Pseudo < ApplicationRecord
  belongs_to :user
  has_one :currentuser, foreign_key:"pseudo_id", class_name:"User"
  def image=(uploaded_io)
  File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
      file.write(uploaded_io.read)
  end
  write_attribute(:image, uploaded_io.original_filename)
  end
  def image
    read_attribute(:image)
  end
end

app/controllers/pseudos_controller.rb
class PseudosController < ApplicationController
  before_action :set_pseudo, only: %i[ show edit update destroy choisir ]
  protect_from_forgery except:[:choisir,:quitter]

  # GET /pseudos or /pseudos.json
  def index
    @pseudos = Pseudo.all
  end
  def choisir
        current_user.update(pseudo_id:@pseudo.id)
        UserAppearanceJob.perform_now(@pseudo,current_user)
  end
  def quitter
        current_user.update(pseudo_id:nil)
        QuitPseudoJob.perform_now(current_user)
  end

  # GET /pseudos/1 or /pseudos/1.json
  def show
  end

  # GET /pseudos/new
  def new
    @pseudo = Pseudo.new({user_id: current_user.try(:id)})
  end

  # GET /pseudos/1/edit
  def edit
  end

  # POST /pseudos or /pseudos.json
  def create
    @pseudo = Pseudo.new(pseudo_params)


    respond_to do |format|
      if @pseudo.save
        current_user.update(pseudo_id:@pseudo.id)
        UserAppearanceJob.perform_now(@pseudo,current_user)
        format.html { redirect_to pseudo_url(@pseudo), notice: "Pseudo was successfully created." }
        format.json { render :show, status: :created, location: @pseudo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pseudo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pseudos/1 or /pseudos/1.json
  def update
    respond_to do |format|
      if @pseudo.update(pseudo_params)
        current_user.update(pseudo_id:@pseudo.id)
        PseudoJob.perform_now(@pseudo,current_user)
        UserAppearanceJob.perform_now(@pseudo,current_user)
        format.html { redirect_to pseudo_url(@pseudo), notice: "Pseudo was successfully updated." }
        format.json { render :show, status: :ok, location: @pseudo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pseudo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pseudos/1 or /pseudos/1.json
  def destroy
    @pseudo.destroy

    respond_to do |format|
      format.html { redirect_to pseudos_url, notice: "Pseudo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pseudo
      @pseudo = Pseudo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pseudo_params
      params.require(:pseudo).permit(:user_id, :name, :body,:image)
    end
end

app/helpers/pseudos_helper.rb
module PseudosHelper
end

app/views/pseudos/_form.html.erb
<%= form_with(model: pseudo) do |form| %>
  <% if pseudo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pseudo.errors.count, "error") %> prohibited this pseudo from being saved:</h2>

      <ul>
        <% pseudo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.hidden_field :user_id %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>
  </div>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pseudos/_pseudo.html.erb
<article data-pseudo-id="<%=pseudo.id%>"  data-current-user-id="<%=pseudo.currentuser.try(:id)%>">
        <img src="/uploads/<%=pseudo.image%>" width=50 height=50 />
              <p><%=pseudo.name%></p>
                    <p><%=pseudo.body%></p>
                        </article>

app/views/pseudos/edit.html.erb
<h1>Editing pseudo</h1>

<%= render "form", pseudo: @pseudo %>

<br>

<div>
  <%= link_to "Show this pseudo", @pseudo %> |
  <%= link_to "Back to pseudos", pseudos_path %>
</div>

app/views/pseudos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pseudos</h1>

<div id="pseudos">
  <% @pseudos.each do |pseudo| %>
    <%= render pseudo %>
    <p>
      <%= link_to "Show this pseudo", pseudo %>
    </p>
  <% end %>
</div>

<%= link_to "New pseudo", new_pseudo_path %>

app/views/pseudos/new.html.erb
<h1>New pseudo</h1>

<%= render "form", pseudo: @pseudo %>

<br>

<div>
  <%= link_to "Back to pseudos", pseudos_path %>
</div>

app/views/pseudos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pseudo %>

<div>
  <%= link_to "choisir ce pseudo", choisir_pseudo_path(@pseudo),onclick: "choisirpseudo(event);return false;" %> |
  <%= link_to "Edit this pseudo", edit_pseudo_path(@pseudo) %> |
  <%= link_to "Back to pseudos", pseudos_path %>

  <%= button_to "Destroy this pseudo", @pseudo, method: :delete %>
</div>